name: llama3-rocm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch --index-url https://download.pytorch.org/whl/rocm5.6
      - transformers
      - datasets
      - peft
      - accelerate
      - sentencepiece
